version: '3'
services:
  backend:
    build: .
    ports:
      - 12345:9000
    volumes:
      - ./backend:/home/quary/shop/backend
    working_dir: /home/quary/shop/backend
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URL
      - APP_COOKIES_DOMAIN
    command: bash -c "source /home/quary/.sdkman/bin/sdkman-init.sh && sbt run"
  frontend:
    build: .
    ports:
      - 12346:3000
    volumes:
      - ./frontend:/home/quary/shop/frontend
    working_dir: /home/quary/shop/frontend
    command: bash -c "npm install --save && npm start"
