version: '3'
services:
  ebiznes:
    build: .
    ports:
      - 12345:9000
      - 12346:3000
    volumes:
      - .:/home/quary/shop/
    working_dir: /home/quary/shop/backend
    command: bash -c "source /home/quary/.sdkman/bin/sdkman-init.sh && sbt run"